# Generated by Django 5.0.4 on 2024-04-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_vote_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='picture',
            field=models.ImageField(default='pictures/default_pic.jpg', upload_to='pictures'),
        ),
    ]
