# Generated by Django 5.0.4 on 2024-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_voter_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='picture',
        ),
        migrations.AddField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(default='pictures/default_pic.jpg', upload_to='pictures'),
        ),
    ]
