# Generated by Django 5.0.4 on 2024-04-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_remove_voter_picture_candidate_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(default='pictures/default_pic.jpg', upload_to='pictures/'),
        ),
    ]
