# Generated by Django 5.0.4 on 2024-04-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_alter_candidate_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(blank=True, default='pictures/default_pic.jpg', null=True, upload_to='pictures/'),
        ),
    ]
