# Generated by Django 5.0.4 on 2024-05-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_election_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_active',
        ),
    ]
