# Generated by Django 5.0.4 on 2024-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_remove_election_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='image',
            field=models.ImageField(blank=True, default='pictures/abstract-gradient.jpg', null=True, upload_to='pictures/'),
        ),
    ]
