# Generated by Django 5.0.4 on 2024-11-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0013_alter_sentemail_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name="election",
            name="categories",
            field=models.ManyToManyField(blank=True, to="election.category"),
        ),
    ]
