import urllib
import json

from votingsystem import settings


def verify_recaptcha(recaptcha_response):
    """
    Verify the reCAPTCHA response token with Google's reCAPTCHA API.

    Parameters
    ----------
    recaptcha_response : str
        The reCAPTCHA response token generated by the reCAPTCHA widget.

    Returns
    -------
    bool
        True if the reCAPTCHA response is valid and successful, False otherwise.

    Notes
    -----
    This function sends a request to Google's reCAPTCHA API to verify the validity of the provided
    reCAPTCHA response token. It uses the site's secret key (CAPTCHA_PRIVATE_KEY) along with the
    response token to verify the CAPTCHA. The function returns True if the CAPTCHA verification is
    successful, indicating that the user is not a robot. Otherwise, it returns False.
    """
    data = urllib.parse.urlencode({
        'secret': settings.CAPTCHA_PRIVATE_KEY,
        'response': recaptcha_response
    }).encode('utf-8')
    req = urllib.request.Request('https://www.google.com/recaptcha/api/siteverify', data=data)
    response = urllib.request.urlopen(req)
    result = json.loads(response.read())
    return result.get('success', False)
